### ISSUE TITLE
Zero fee send results in 0.0001 fee

### ISSUE THREAD

**Issue by ksedgwic** [ksedgwic/Wallet32#1]

**Comment by mmazi** [comment]
Doesn't bitcoinj contain a smart automatic fee calculator? Perhaps this should be used by default. Or perhaps just provide an option to either pay the calculated fee, or no fee, to simplify things for the user.

**Comment by ksedgwic** [comment]
I'll investigate, I think you're correct ... may need a newer version of bitcoinj for this as well ...

**Comment by ksedgwic** [comment]
Fixed in version-0.1.5.

Now you can set even 0 fee, of course transaction may not be accepted by miners ... ;-)
