### ISSUE TITLE
Cannot install on Tablet

### ISSUE THREAD

**Issue by prusnak** [ksedgwic/Wallet32#14]
For some reason the app is not showing on my tablet Play Store (Android 4.1). When I click on the link manually form browser the Play Store says the app is not compatible with my device.

**Comment by karelbilek** [comment]
ahoj :) ,

this is a problem with all the devices without a back camera (I think).

It was solved here #10 , it is now in alpha version (or beta... I am not sure) on Play Store

**Comment by prusnak** [comment]
It has a back camera but I am not sure if this triggers the issue.

**Comment by ksedgwic** [comment]
I've pushed v0.3.3 (and subsequently v0.3.4) to the store, please let me know if they fix the problem.

**Comment by ksedgwic** [comment]
Haven't heard of this bug recently.
