### ISSUE TITLE
Default recovery version

### ISSUE THREAD

**Issue by slush0** [ksedgwic/Wallet32#15]
Hi,

currently, v0.4 is the default version in wallet recovery process. Using current version as a default value seems better to me. When the user create a wallet and try to do recovery (as a confirmation that the backup is fine), incorrect wallet is restored.

Also as application's userbase is rapidly growing, using older version for recovery will be the wrong choice for majority of users.

**Comment by ksedgwic** [comment]
Fixed in version 0.3.6, pushed to alpha.
