### ISSUE TITLE
Allow using BIP-39 passphrase

### ISSUE THREAD

**Issue by prusnak** [ksedgwic/Wallet32#18]
In "Restore wallet" function there is no field for entering the passphrase.

Suggestion: adding a new optional field for passphrase, then using it in BIP39 generation procedure.

**Comment by ksedgwic** [comment]
Fixed in version 0.3.8,  just pushed to alpha in the play store. 

How important are word lists of 18 and 24 words?   Should I add support for those too?

**Comment by prusnak** [comment]
Wordlist is the same for every length (12, 18, 24). 

Do you check for length of mnemonic in the Restore dialog? If yes, then you should accept not only 12 words, but also 18 and 24.

**Comment by prusnak** [comment]
Also it is a good idea to check the mnemonic as a whole has the correct checksum (check method in https://github.com/trezor/python-mnemonic/blob/master/mnemonic/mnemonic.py#L86) and show a warning if it does not.

**Comment by ksedgwic** [comment]
I've added support for 18 and 24 word lists in Wallet32-0.3.12 (currently in beta).  Confirmed compatibility with Trezor.

**Comment by prusnak** [comment]
Great, thanks!
