### ISSUE TITLE
HD Wallet import key

### ISSUE THREAD

**Issue by geopayme** [ksedgwic/Wallet32#32]
I have an offline HD wallet... but I cant seem to be able to sweep my HD wallet extended private key into the wallet. Are there any specific procedures or instructions I need to follow or the wallet32 only sweeps hd wallet keys generated ONLY by the wallet32 app?

**Comment by ksedgwic** [comment]
Adonis,

The sweep private key function is for discrete private keys (think basic
paper wallets).  Wallet32 does not have a feature
to import or sweep xpubs.

myTrezor Lite can import xpubs and view and receive funds:

http://satoshilabs.com/news/2014-09-25-introducing-mytrezor-lite-for-android/

Hope this helps ...

Ken

On Wed, Apr 1, 2015 at 2:38 AM, Adonis Valamontes notifications@github.com
wrote:

> I have an offline HD wallet... but I cant seem to be able to sweep my HD
> wallet extended private key into the wallet. Are there any specific
> procedures or instructions I need to follow or the wallet32 only sweeps hd
> wallet keys generated ONLY by the wallet32 app?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ksedgwic/Wallet32/issues/32.

## 

Ken Sedgwick
Bonsai Software, Inc.
http://www.bonsai.com/ken/
(510) 269-7334
ken@bonsai.com
Public Key: http://www.bonsai.com/ken/ken.asc
GPG Fingerprint: 851E 3B07 E586 0843 9434  5CC7 4033 3B9B 3F3F 9640

**Comment by geopayme** [comment]
Thanks for the reply Ken,

I downloaded the android app, but it seems that you need to have a hardware device to use it.

I think for those who choose to take the HD wallet road its an up hill battle to find a consumer solution without having to create one from scratch.

**Comment by ksedgwic** [comment]
Pretty sure the myTrezor lite does not require a device:

https://play.google.com/store/apps/details?id=com.satoshilabs.btcreceive

Ken

On Wed, Apr 1, 2015 at 12:24 PM, Adonis Valamontes <notifications@github.com

> wrote:
> 
> Thanks for the reply Ken,
> 
> I downloaded the android app, but it seems that you need to have a
> hardware device to use it.
> 
> I think for those who choose to take the HD wallet road its an up hill
> battle to find a consumer solution without having to create one from
> scratch.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ksedgwic/Wallet32/issues/32#issuecomment-88601935.

## 

Ken Sedgwick
Bonsai Software, Inc.
http://www.bonsai.com/ken/
(510) 269-7334
ken@bonsai.com
Public Key: http://www.bonsai.com/ken/ken.asc
GPG Fingerprint: 851E 3B07 E586 0843 9434  5CC7 4033 3B9B 3F3F 9640

**Comment by geopayme** [comment]
I can't go past this section of the app. that's the first screen.

**Comment by geopayme** [comment]
Thanks for the effort Ken,

I will close this issue. Ultimately I will have to look at wallet32 to see if that could be a foundation to a new solution.

Best Regards

Adonis
