### ISSUE TITLE
Support decimal comma

### ISSUE THREAD

**Issue by mmazi** [ksedgwic/Wallet32#4]
Some countries like Germany and France use [decimal comma](http://en.wikipedia.org/wiki/Decimal_mark#Countries_using_Arabic_numerals_with_decimal_comma). This is only partially supported: comma is automatically used in the input fields, but fails to parse when submitting.

![screenshot_2013-12-27-00-34-32](https://f.cloud.github.com/assets/294075/1814350/270f715c-6ee9-11e3-9b71-0cda5fb2429c.png)

**Comment by mmazi** [comment]
The comma can then be manually changed into a period, then the sending works.

**Comment by ksedgwic** [comment]
Added workaround in version 80acae385cbb5c1edaedcee4aa082591e2a5a9e9

**Comment by mmazi** [comment]
This now works without having to manually change the comma to period. 

A slight remaining issue is that the amount, before it's entered, still uses decimal period instead of comma.

![media-20131229](https://f.cloud.github.com/assets/294075/1819408/f904496c-708d-11e3-9938-45d80ced9e46.png)
