### ISSUE TITLE
Display clipping issues

### ISSUE THREAD

**Issue by mmazi** [ksedgwic/Wallet32#5]
On Samsung Glaxy S some text is clipped at borders:

![screenshot_2013-12-27-00-32-48](https://f.cloud.github.com/assets/294075/1814353/58160af4-6ee9-11e3-84bf-9ce9cb31667a.png)
![screenshot_2013-12-27-00-32-23](https://f.cloud.github.com/assets/294075/1814354/5ae4c2ac-6ee9-11e3-9e4e-83ee662b60f7.png)

**Comment by ksedgwic** [comment]
Matija,

I've adjusted the layout in 8adb443a84e70090fe45ad352e73ab188cd08642 (version 0.1.4).

I'm using the emulator's Nexus One setting to judge the clipping effects.

Could you take another look and see if I've fixed the layout issues on your device?

Thanks in advance!

Ken

**Comment by mmazi** [comment]
Still slightly clipped on the right side.
![media-20131229](https://f.cloud.github.com/assets/294075/1819408/f904496c-708d-11e3-9938-45d80ced9e46.png)

**Comment by mmazi** [comment]
Oh, and it's quite bad in landscape mode since there is no scrolling so top and bottom inputs/buttons are inaccessible.

Landscape mode should probably be disabled.

**Comment by ksedgwic** [comment]
Hmm ... this only gets worse if you name your account "My Business Account" or another reasonably long name.

Also, I need to add an "Available Balance" column as well, to omit the unconfirmed btc that are not ready to be sent.

I think a stronger solution is needed.  Maybe the tabular layouts need to use multiple lines per entry?

**Comment by mmazi** [comment]
Why not just reuse some of the Shildbach's wallet's design? (Or even most of the code?) I find their layout very effective.

**Comment by ksedgwic** [comment]
Wallet layout refactored.  I believe this case is addressed.

Plan to move to multiple line per row layout, will be an even better solution.
