### ISSUE TITLE
Cannot spend unconfirmed UTXO

### ISSUE THREAD

**Issue by slush0** [ksedgwic/Wallet32#9]
Hi,

currently only confirmed transactions can be spent (tested on 0.2.5). It would be awesome to enable spending unconfirmed utxo as well.

Thanks!
slush

**Comment by karelbilek** [comment]
I am not sure if this is good idea. 

"Chaining" of unconfirmed transactions can lead to problems; if one transaction in the chain is problematic/double-spend/changed via malleability/low fee, and so on, the whole chain goes down.

I think users should not think of unconfirmed transactions as spendable.

This is just my opinion though.

**Comment by dabura667** [comment]
I +1 runn1ng's perspective as a default option.

However, I think there should be an advanced options menu with enabling spend of unconfirmed. (maybe the hidden menu when you tap the about walrus.)

**Comment by ksedgwic** [comment]
I've added an "Unconfirmed Balances Spendable" preference when the app has advanced/experimental features enabled.  This is in version 0.3.4, just pushed to alpha (also available here : https://www.bonsai.com/ken/public/Wallet32.apk).

To enable advanced/experimental features tap on the Walrus in the About page 10 times.

**Comment by slush0** [comment]
There was quite long discussion between wallet developers year or more ago about such feature and its pros and cons. The conclusion of that flamewar was that all known wallets allow spending unconfirmed tx by default, and I think it may be especially useful for mobile wallets, where users handle fairly small amounts (so nobody really cares about double spending), but they usually want their mobile coins to be always spendable. Imagine guy who just recieved few cents from his friend and now he must wait in bar until he's able to pay his bill. At least he'll drink another beer, so Wallet32 indirectly supports alcoholism!

However having such feature in "advanced" mode is probably good compromise, at least advanced users will save their livers ;).

**Comment by ksedgwic** [comment]
Closing this bug, feature is available in advanced mode.
